---
# the name of the file could be anything

name: checks

# the triggers on which the tasks have to be run
on: [push]

jobs:
  # test-lint is the job id. It could be referenced somewhere else, for example when u want to configure the dependency
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    # the steps are executed in the order they are put in this file
    steps:
      - name: Login to Docker hub
      #  this is a pre built action available out of the box in the github. The below action is a docker container available in the docker repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name : Lint
        run: docker-compose run --rm app sh -c "flake8"
